apiVersion: v1
kind: Secret
metadata:
  name: meldit-secrets
  namespace: meldit
type: Opaque
stringData:
  database_url: "postgresql://postgres:example@postgres:5432/meldit"
  redis_url: "redis://redis:6379/0"
  proxy_list: ""


