global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scraper'
    static_configs:
      - targets: ['scraper:8001']

  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:8002']

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:8501']


